### ISSUE TITLE
Find Prettier in nested package.json project

### ISSUE THREAD

**Issue by bolivier** [jscheid/prettier.el#118]
**Is your feature request related to a problem? Please describe.**

I primarily work in a codebase with a root level package.json and nested package.json files.  In this instance the root package.json has the prettier dependency listed.  

`prettier.el` only searches for the most immediate package.json file and then moves on to other locations.  

**Describe the solution you'd like**
I would like the search process to check nested package.json files so that if it's installed in the project, but not the most immediate package.json, prettier.el will work as normal.

**Describe alternatives you've considered**
What has worked for most of the time is using a global install pinned to the version I use, but I recently noticed that prettier.el is not using the globally installed version of prettier.

**Additional context**

I'm happy to work on a solution to this myself, but I'm not particularly well versed in building things with elisp.

**Comment by jscheid** [comment]
Hi, thanks for the detailed write-up. It definitely sounds like something that should work better.

Could you share a few more details about your setup? I'm pretty sure I've used prettier.el many times with packages nested via [yarn workspace](https://classic.yarnpkg.com/lang/en/docs/workspaces/) and things always seemed to work as they should. I assume you're not using Yarn?

**Comment by bolivier** [comment]
That's right, I'm using npm and not yarn. 

The project structure is something like this, and as noted `prettier` is only installed in the root package.json

```
my-app/
├─ client/
|  ├─ package.json (for client)
├─ const/
│  ├─ package.json (for const)
├─ package.json (for root, where prettier is installed)
├─ const/
│  ├─ index.js
```

As best I can tell, it's defaulting to an older globally installed version in the client code.  I've managed to sync the version number from `M-x prettier-info` and the root package.json.

**Comment by bolivier** [comment]
@jscheid I think I have more context on this, which is that my nested package.json has a dependency install of prettier and that's what's being used.  

Ideally I could manually set a version/executable of Prettier  to use, but given the js server, I'm not sure the best way to go about configuring that.  Do you have any thoughts on it?

**Comment by jscheid** [comment]
> my nested package.json has a dependency install of prettier and that's what's being used.

I assume you mean a transient dependency. Can you install a non-transient (direct) dependency on prettier in the package? If so, that one should be picked up instead of the transient dep. (I'm not sure I've ever tested this but if it doesn't work, I'd consider that a bug.)

Alternatively, can you remove the transient dep? A couple ways I can think of:
- There's a chance the transient dep is declared non-dev by accident? If you can get the dependent package to fix this, the problem should go away (because devDependencies of dependencies aren't installed.)
- If using Yarn you could [hack it](https://github.com/yarnpkg/yarn/issues/4611#issuecomment-1595182653), admittedly not a very clean solution but similar ones might exist for other package managers.

> Ideally I could manually set a version/executable of Prettier to use

There's currently no provision for doing this: the way to select the Prettier version is to install it at that location (via `package.json`.) We could conceivably add an override but that would be some work and it would complicate matters, I'd like to avoid it if possible.

**Comment by seh** [comment]
_s/transient/transitive/g_, right?

**Comment by bolivier** [comment]
> the way to select the Prettier version is to install it at that location 

It works as expected when I install it as a dev dependency.  

I still think it'd be nice to select an install manually, but it's probably best to leave it as is.  My issue is annoying but should be resolved outside this package, I think.  Closing since there's nothing to address here.
