### ISSUE TITLE
.prettierignore file content is ignored.

### ISSUE THREAD

**Issue by farynaio** [jscheid/prettier.el#67]
**Is your feature request related to a problem? Please describe.**
Project specific `.prettierignore` file content is ignored. It makes impossible to keep formatting consistency when `.prettierignore` is provided and used by the rest of the team.

**Describe the solution you'd like**
`.prettierignore` file content will be used to decide if file should be included or ignored by Prettier formatter.

**Describe alternatives you've considered**
don't know any

**Additional context**
none

**Comment by jscheid** [comment]
Good catch @farynaio. I'm going to dogfood the fix for a few days before releasing it. If you'd like to use it sooner, you can download the tarball from [here](https://github.com/jscheid/prettier.el/suites/1909110736/artifacts/37496756) and install it with `M-x package-install-file` (you have to peel off the zip layer but not the tar layer.)

**Comment by jdelStrother** [comment]
Did this ever get released? I'd like to try the tarball, but it seems to have expired.

**Comment by jscheid** [comment]
Yes, it did get released. Does it not work for you?

**Comment by jscheid** [comment]
Ah right, it's not in stable. I should probably cut a new release, thanks for the heads up.
