### ISSUE TITLE
Does not respect `.prettierignore`

### ISSUE THREAD

**Issue by bolivier** [jscheid/prettier.el#91]
**Describe the bug**
Commands do not respect ignoring as specified in a `.prettierignore` file. 

**Link to `M-x prettier-info` output**
https://gist.github.com/bolivier/9a3e27a481805f9dffcdfcaca5de2c1e

**To Reproduce**

* Create a new directory
* `npm init -y`
* `npm i --save prettier`
* create a source file, and add it to a `.prettierignore` file
* run `prettier-js` and see that the file is formatted anyway

**Expected behavior**
The file should be ignored by prettier based on the ignore file.

**Additional context**
None.

**Comment by jscheid** [comment]
Did you mean to put this over at https://github.com/prettier/prettier-emacs ? This repo is for the `prettier`, not the `prettier-js` package.

**Comment by jscheid** [comment]
I think you might be using both our package (which provides `prettier-info`) and the other package (which provides `prettier-js`). You should probably uninstall one of the two, to reduce confusion.

If you want to run our code on demand, use `prettier-prettify`.

This package used to ignore `.prettierignore` but that bug [is fixed](https://github.com/jscheid/prettier.el/pull/68) and there's a [test case](https://github.com/jscheid/prettier.el/tree/master/test-cases/prettierignore) for it.

**Comment by bolivier** [comment]
I'm very confused because it seems like you're right, but I have no reference to `prettier-emacs` anywhere in my `.emacs.d` directory.

**Comment by jscheid** [comment]
That package is called `prettier-js`, only the repository is called `prettier-emacs`. Maybe that's why you can't find it?

In your defense the situation _is_ maximally confusing:

| Repository name                                           | Emacs Package name |
| --------------------------------------------------------- | ------------------ |
| [prettier-emacs](github.com/prettier/prettier-emacs)      | prettier-js        |
| [prettier.el](github.com/jscheid/prettier.el) (this repo) | prettier           |
